Rai RPM Repository for RedHat Based Systems
===========================================
:toc: left

About
-----

The open source caching and distribution components that are designed by Rai
are built for RPM based software installation and are stored in this repo.
There is at least one package
(link:http://oldhome.schmorp.de/marc/liblzf.html[liblzf]) that lives in the
link:https://fedoraproject.org/wiki/EPEL[EPEL repo], so that may also be needed
for RedHat Enterprise / CentOS based distributions.

The RPM files here are built from their github clones on link:https://copr.fedorainfracloud.org/coprs/injinj/rel/[copr].

- link:https://github.com/injinj/raims[Rai MS], a link state router for
  multicast services (package: raims)

- link:https://github.com/injinj/raikv[Rai KV], a shared memory key
  value store (package: raikv)

- link:https://github.com/injinj/raids[Rai DS], distribution services,
  including Redis, Memcached, Http, WebSocket, DS API (package: raids)

- link:https://github.com/injinj/raimd[Rai MD], market data codecs,
  including TIB/SASS, Marketfeed, RV, RWF, Json, Dictinaries (package: raimd)

- link:https://github.com/injinj/sassrv[SASS RV], RV protocol bridge
  (package: sassrv)

- other packages that are dependencies of the above, the `git submodule`
facility links the package within the git source trees on github.

Installing
----------

Download one of the following repo files and install it to `/etc/yum.repos.d/`.

- RedHat 7,8,9,etc, link:raitechnology_epel-x86_64.repo[raitechnology_epel-x86_64.repo]
- Fedora 39,40,41,etc, link:raitechnology_fedora-x86_64.repo[raitechnology_fedora-x86_64.repo]

Then use `yum` or `dnf` to install packages.

Example
-------

This example uses `curl` to install, then `yum` to install the raids package
which has several dependencies.  These are resolved, then the GPG public key
used to verify the RPMs, is imported by `yum`.

----
$ sudo curl -s https://www.raitechnology.com/repo/raitechnology_epel-x86_64.repo -o \
/etc/yum.repos.d/raitechnology_epel-x86_64.repo

$ sudo yum install raims
----

Description
-----------

The RPM installers, *yum* or *dnf* can be used when the repo file is
installed.  This file usually lives in a well known directory
`/etc/yum.repos.d/raitechnology_epel-x86_64.repo` and needs two links:

1.  The RPM directory contains the rpm files:

- link:epel-7-x86_64[epel-7-x86_64] -- RHEL 7
- link:epel-8-x86_64[epel-8-x86_64] -- RHEL 8
- link:epel-9-x86_64[epel-9-x86_64] -- RHEL 9
- link:fedora-39-x86_64[fedora-39-x86_64] -- Fedora 39
- link:fedora-40-x86_64[fedora-40-x86_64] -- Fedora 40
- link:fedora-41-x86_64[fedora-41-x86_64] -- Fedora 41

2.  The GPG public key used to verify the package file:

- link:RPM-GPG-KEY-raitechnology[RPM-GPG-KEY-raitechnology]

The contents of the repo file contains these links, and looks like this:

----
[raitechnology]
name=Rai Technology epel-$releasever-x86_64
baseurl=https://www.raitechnology.com/repo/epel-$releasever-x86_64
enabled=1
gpgcheck=1
gpgkey=https://www.raitechnology.com/repo/RPM-GPG-KEY-raitechnology
----

When this file is enabled, yum/dnf will be able to resolve the dependencies
required for installing any of the packages.
