Rai Protocol for Cache Backed Pub Sub
=====================================
:toc: left

About
-----

This document describes a caching layer on top of existing pubsub systems.
Pubsub provides for a multiplexed subject adressed based stream of messages
from publisher to subscriber.  Pubsub is usually layered on top of a reliable
based transport, such as *TCP* or *PGM*.  The multicast supported by the
architectures is either point to point *TCP* fanout of subscription interest or
built on top of a reliable multicast *UDP* transport.  The publisher can be a
feed service, performing last value caching and trasforming the events into
subject streams, or it may be a cache based router, which distrubutes publisher
services across multiple nodes in order to scale networks.

The caching layer includes methods for synchronizing state distributed across a
network of nodes.  The most important of this extended functionality is
subscription management, which includes methods beyond pubsub that allow for
network endpoints, the publisher and the subscriber, to encode cache semantics,
fault tolerance, and subscription visibility.

Subscription Operations
------------------------

Subscription Listen
~~~~~~~~~~~~~~~~~~~

A message from a subscriber that multicasts to a well known endpoint with
notification of a subscripion start.  This message contains infromation
identifying the subscriber uniquely.

Subscription Intial
~~~~~~~~~~~~~~~~~~~

This extends the subscription listen to also provide a subscriber endpoint for
intializing the image associated with the subscription.

Snapshot Intial
~~~~~~~~~~~~~~~

A one time request for the current state of the cached image.

Unsubscribe
~~~~~~~~~~~

This message multicasts to the well known endpoint with a notification of a
subscription stop using the unique identification sent with the subscription
start.

Reassert Subscription
~~~~~~~~~~~~~~~~~~~~~

This message resets any timers associated with subscription by the publisher.
A publisher may drop subscriptions that have not been active after a period of
time.

Update Messaging
----------------

Update Publish
~~~~~~~~~~~~~~

After one or more subscription interestes are known, the publisher provides
updates to the subscription.

Refresh Initial
~~~~~~~~~~~~~~~

In the event that a subject stream is disrupted by network or node failure,
this reestablishes the initial state of the subject, which has become stale.

Drop Notification
~~~~~~~~~~~~~~~~~

In the event that a subscription timer expires, this notifies any subscriber
that may be active that the publisher dropped the subscription and is no longer
forwarding messages.  If a subscriber is still active, it must reasert or
restart the subscription.

Stale Notification
~~~~~~~~~~~~~~~~~~~

If the publisher is no longer able to provide updates or has lost sequences of
messages associated with a subject, this notifies the subscriber that the
current state is stale.  This may cause subsribers to restart a subscription on
another path or they may need to wait for the publisher to restore the subject
stream.

Not Found Notification
~~~~~~~~~~~~~~~~~~~~~~

When a subscription listen starts, this reply notifies the subscriber that the
subscription is established, but that no published data is currently available.

Verify Notification
~~~~~~~~~~~~~~~~~~~

Another form of subscription listen start reply where the publisher notifies
that no published data is available, but is expected to be ready soon.  This
often includes a zeroed record associated with the subject so that the
subscriber can initialize its internal state and be ready for updates.

Feed Down
~~~~~~~~~

A form of stale notification that may include information about the publisher
state.

Feed Switch
~~~~~~~~~~~

A form of stale notification that indicates a gap or duplication of the stream
may occur as the source path of the stream has changed, such as a primary to
secondary flip.

Subscription Expired
~~~~~~~~~~~~~~~~~~~~

If a subject stream is permanently ended, this notifies that the publisher no
longer intends send updates.

Subject Renamed
~~~~~~~~~~~~~~~

When a subject stream is renamed to another, this message identifies which
subject should be subscribed to reestablish the stream.

Recap Publish
~~~~~~~~~~~~~

When a feed switch, or primary to secondary flip, occurs, a recap of the latest
updates are published in order to insure that the stream is up to date.  These
messages can be combined so that all of the data up to the last published
update are recapped for the configured time period.

Conflated Publish
~~~~~~~~~~~~~~~~~

If a subject stream has reduced bandwidth, a conflated message encodes multiple
updates into a single update.  This allows a publisher to increase the
reliability with a reduction in message rate when the latency of updates is not
as important.

Other Services
--------------

Dictionary
~~~~~~~~~~

If a dictionary is associated with the messages sent, this well known endpoint
can be used by subscribers to download the latest dictionary.  If a dictionary
is not static, subscription for dictionary updates is also started.

Entitlements
~~~~~~~~~~~~

When a system is designed for licensed access to data, it is necessary to track
the activity of the subscriber.  This service endpoint encodes the access
levels and the logging of subscription events.

Service Directory
~~~~~~~~~~~~~~~~~

A subject space is often divided into seperate services, each with it's own
well known endpoint for establishing a subscriptions.  Traditionally, the first
segment of the subject identifies the publsher.  For example, NASDAQ may be
used to establish subscriptions published by the NASDAQ feed, and NYSE may be
used for the NYSE feed.  The service directory names all of the publishers by
their subject prefix.  It should also define the dictionary and entitlements
well known endpoints if they are desired.

Protocols Supported
-------------------

The target systems, except for *RV* employ text based publish and subscribe
primitives.  For this reason, the protocol for supporting extended semantics
should have a text base, with an equivalent binary format.  This is expanded
in <<Format>>.

RV
~~

The *SASS2* and *SASS3* protocols are built on top of RV, but are not natively
equiped to to deal with the some of field types needed such as a decimal type
that maintains the precision of the numerical data.  In most cases, the system
that need these types, use alternative message formats passed in *OPAQUE*
fields.

The <<Legacy>> section below describes how the *SASS2* and *SASS3* protocols
work.  The goal of this section is to show the strengths and the weaknesses of
these and inform the design of the protocol layers needed to extend the other
protocols.

NATS
~~~~

NATS does not natively have subscription management, so much of the caching
semantics has to be layered on top of the base pubsub system.  The subject
encoding scheme is mostly *RV* compatible, with the exception of publishing
messages to wildcard subjects, which is forbidden.

Redis
~~~~~

Redis also does not nately have subscripton management, but it does have a
complex array of caching semantics that may be used.  The subject encoding
is string based with shell style wildcards.  Users *Redis* often segment
the channels (subjects) using a ':' separator.

Http/Websocket
~~~~~~~~~~~~~~

This is basically the same as the Redis case, since the caching semantics
works as the Redis RESP protocol is layered over the Websocket protocol.

OpenPGM
~~~~~~~

This is a transport, not a pubsub sytem.  The history of PGM flows through
early caching systems by Tibco, to RFC, to open source.  A pubsub layer could
design any subject encoding scheme.

[[Legacy]]
Legacy RV SASS2 and SASS3
-------------------------

Overview
~~~~~~~~

With the *SASS2* base, most of the RV architecture already supports many of the
features needed for subscription visibility and identifying the subscriber.
The most annoying features of *SASS* is the static dictionary and the lack of
formalizing the sequence numbers of the updates.  There are two forms of
sequencing which use the same *SEQ_NO* field.  The publisher may use the
*SEQ_NO* field for sequencing the stream of data, across multiple subjects but
the subscriber needs the sequencing for each subject.  This segmentation
requires subscriber to know what variation of sequencing is used in order to
verify the sequences of updates.

The *SASS2* header includes *MSG_TYPE*, *REC_TYPE*, *SEQ_NO*, *REC_STATUS*.
The *MSG_TYPE*, *REC_STATUS* fields encode the basic response types needed,
with an optional status *TEXT* field for descriptions.  The *REC_TYPE* is
deprecated as an advisory field, as support for dictionary based record
encoding as been erroded by field additions and the pain of updating a static
dictionary in a distributed system.

The subscription management is built into the RV system.  Each unique endpoint
identifies itself using the IP address of the interface and a timestamp of the
daemon startup.  The subscriptions are reasserted every 90 seconds by
publishing a *HOST.STATUS* message.  When the transport is disrupted, the
subscriptions can be obtained from the host by querying it.  Each host is
reachable on a well known subject *_INBOX.hostip.DAEMON*.  The main drawback of
this management method is the 90 seconds interval, which can lead to long
periods of outages bounded by 90 second intervals before a subject stream
reestablishes the cached state.  Any switch or network element in between the
subscriber and the publisher which drops the multicast *UDP* packets can cause
a a long disruption in the subscriptions that were dropped.

The advantages of *SASS2* are that it is a low overhead system without a lot of
subscription management traffic during normal operation.  The successor to
*SASS2*, called *SASS3*, adds reassert type messages and each subscriber
publishes these on a randomized interval.  The *_INBOX.hostip.DAEMON* is no
longer supported since the Tibco archetecture introduced subject based routers
(rvrd) where the network *IP* addresses may be using *NAT* translation between
segments or may not be directly reachable through *IP* routers.  When these are
present, the *_INBOX* addresses used for point to point communication are
modified as they progress through the *rvrd* routers.  For example, a
*_INBOX.hostip.timestamp.N* subscriber endpoint is modified to be
*_INBOX.routerip.timestamp._INBOX.hostip.timestamp.N*.  This type of
infrastructure using *rvrd* is uncommon.  Reuters used its own method for
connecting across network boundaries through the use of it's market data hub
products which contained the *SASS2* and *SASS3* protocols because the finance
portion of Tibco products were transfered to Reuters.

Subscription Listen/Unsubscribe
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The *SASS2* portion of the subscription mechanics are defined by the basic
operation of *RV*, they were organically defined in the original *SASS* market
data platform and evolved into *RV*.

*SASS2* Subscription Request
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A subscription generates this message:

   _RV.INFO.SYSTEM.LISTEN.START.subject : {
     return : _INBOX.hostip.timestamp.N,
     data : {
       ADV_CLASS : INFO,
       ADV_SOURCE : SYSTEM,
       ADV_NAME : LISTEN.START.subject
       id : hostip.timestamp,
       sub : subject,
       refcnt : counter
     }
   }

The *sub* and *id* fields identify the subject and the subscriber making the
subscription, the optional return field requests that an inital response is
desired.  In recent versions of the Tibrv API, it is not possible to specify
the return field in a subscription request.  The *refcnt* is incremented and
decremented by the same subscriber *id* starting the same subscription.  This
is uncommon since most Tib APIs will not allow this.

SASS2 Snapshot Request
^^^^^^^^^^^^^^^^^^^^^^

A well known endpoint that receives:

  _SNAP.subject : {
    return : _INBOX.hostip.timestamp.N,
    flags : mask
  }

The snapshot image is returned to the *_INBOX* address.  The optional flags can
additionally specify that a subscription should start (flags = 6, the same as
the *T* flag in *SASS3* request described below).  This allows Tibrv API
subscriber to request an initial value with a return *_INBOX*, which is no
longer possible with the *LISTEN.START* message when using the Tibrv API.

SASS2 Unsubscribe Request
^^^^^^^^^^^^^^^^^^^^^^^^^

An unsubscribe generates this message:

   _RV.INFO.SYSTEM.LISTEN.STOP.subject : {
     data : {
       ADV_CLASS : INFO,
       ADV_SOURCE : SYSTEM,
       ADV_NAME : LISTEN.STOP.subject,
       id : hostip.timestamp,
       sub : subject,
       refcnt : counter
     }
   }

SASS3 Subscription Request
^^^^^^^^^^^^^^^^^^^^^^^^^^

A well known endpoint is defined for each service on a subject domain, for
example, *_SASS.NASDAQ.SUB*.  This message is published by the subscriber for
subscription operations:

  _SASS.svc.SUB : {
    return : _INBOX.hostip.timestamp.N,
    data : {
      M : sub_magic,
      T : flags,
      A : {
        U : user,
        H : host,
        A : program,
        P : process-id
      }
      S : subject
    }
  }

The *sub_magic* is always the value 23176.  The *S* and *A* fields identify the
subject and the subscriber making the subscription, and the *T* flags is a bit
mask identifing what operation is requested:

[grid=cols,cols=2]
|====
|SNAPSHOT_FLAG        | 0x01
|SUBSCRIBE_FLAG       | 0x02
|INITIAL_VALUES_FLAG  | 0x04
|UNSUBSCRIBE_FLAG     | 0x08
|REFRESH_FLAG         | 0x10
|RESUBSCRIBE_FLAG     | 0x80
|====

The *A* field is commonly combined into a string as *user@host/program#pid*.
This endpoint merges the basic subscription operations: Subscription,
Subscription Image, Snapshot, Refresh Image, Subscription Reassert,
Unsubscribe.  The advantages of a *SASS3* request are that the subsccriber is
identified by a readable string rather than a hostip and timestamp and that
many of the operators for asserting subscriptions are combined into one
publish.  The disadvantage is that the service endpoint needs to be defined and
the host field does not need to identify the IP address of the subscribers
making the request.

Reassert Subscription
~~~~~~~~~~~~~~~~~~~~~

SASS2 Reassert Subscription
^^^^^^^^^^^^^^^^^^^^^^^^^^^

A *SASS2* subscription managment database is necessary to ensure that the
*HOST.STATUS* is updated every 90 seconds.  Every subscription contains an *id*
which identifies the daemon endpoint that can be queried to obtain the current
subscription state.  This is the *HOST.STATUS* message (missing some fields for
brevity):

  _RV.INFO.SYSTEM.HOST.STATUS.hostip : {
    ADV_CLASS : INFO,
    ADV_SOURCE : SYSTEM,
    ADV_NAME : HOST.STATUS.hostip,
    hostaddr : ipaddress,
    time : milliseconds,
    service : service-number,
    network : network-spec
    ...
  }

The *hostip* part of the subject reasserts all subscriptions with the *id*
*hostip.timestamp* or *hostip.DAEMON.timestamp*, which were specified by the
*LISTEN.START* message.  If there is message loss on the transport or the
*HOST.STATUS* message does not get received by the subscription manager at the
time expected, it uses point to point requests to retrieve the current
subscription state.

There are two queries to obtain the state of subscriptions, the session
query and the subscription query.  The session query lists the subscriber
sessions attached to a daemon.  The subscription query lists the subject
attached to a session(s).

The format of the session state queries are:

  _INBOX.hostip.DAEMON : {
    return : _INBOX.hostip.timestamp.N,
    data : {
      op : get,
      what : sessions
    }
  }

The format of the subscripion state queries are:

  _INBOX.hostip.DAEMON : {
    return : _INBOX.hostip.timestamp.N,
    data : {
      op : get,
      what : subscriptions,
      session : hostip.timestamp
    }
  }

The return of the session state query is a list of sessions, which match
the *id* of the *LISTEN.START* notifications:

  _INBOX.hostip.timestamp.N : {
    null : hostip.DAEMON.timestamp,
    null : hostip.timestamp,
    null : hostip.timestamp
  }

Each of these sessions can be used to retrieve the subscriptions using the
subscription state query above, this returns a list of subjects:

  _INBOX.hostip.timestamp.N : {
    user : nobody
    null : subject
    null : subject
    end  : 1
  }

SASS3 Reassert Subscription
^^^^^^^^^^^^^^^^^^^^^^^^^^^

The *_SASS.svc.SUB* method of starting subscriptions can contain a list of
subjects.  Although the list can be used to mass start or stop subscriptions,
the primary use is to reassert them.  After the list is processed by the
manager, an *ACK* is published to the return subject.  If this message is used
for reassert:

  _SASS.svc.SUB : {
    return : _INBOX.hostip.timestamp.N,
    data : {
      M : sub_magic,
      T : RESUBSCRIBE_FLAG,
      A : {
        U : user,
        H : host,
        A : program,
        P : process-id
      }
      S : subject1,
      S : subject2,
      S : subject3
    }
  }

The *T* field is the same as the *SASS3* subscription request above, where 0x80
is the mask bit for *RESUBSCRIBE_FLAG*.

After processing the reassert message, the publisher sends an *ACK* to the
return subject:

  _INBOX.hostip.timestamp.N : {
    data : {
      M : pub_magic,
      I : 0x20,
      T : VERIFY,
      S : OK,
      D : {
        S : subject1,
        S : subject2,
        S : subject3
      }
    }
  }

This is an active method of reasserting compared to the *SASS2* method.  The
advantage of *SASS3* is that the status of the subscriptions can be updated by
the manager as a list.  The *T* and the *S* fields are derived from the
*MSG_TYPE* and *REC_STATUS* fields of the updates.  The *SASS2* passive method
allows for simpler subscribers and both protocols will update the status of the
subjects via update publishes.

Subscription Initial/Snapshot
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In all cases the initial value is sent point to point using the return argument
provided by the subscrtion start.  The first subject that is subscribed by a
*RV* subscriber when the connection is established to the daemon is the
*_INBOX.hostip.timestamp.>* subject, which is globably unique in the *rvd*
subject domain (but not in rvrd's).  All of the return values normally contain
this prefix, since the subscription is already started.  When an inbox is
provided by the Tib APIs, it is incrmenting an integer and appending it to the
base after the timestamp, for example *_INBOX.hostip.timestamp.2*.  The
*_INBOX.hostip* prefix also causes the subject to be routed over point to point
links instead of multicast.  Since the *IP* routing and the reliability of the
protocols is defined for each stream type, the point to point and multicast
messages arrive independent of one another, no ordering between them is
guarenteed.

SASS2 Initial/Snapshot
^^^^^^^^^^^^^^^^^^^^^^

The message arriving using the return subject does not contain the original
subscription subject, so this mapping of *_INBOX* string to subject must be
maintained by the subscriber.  The *SASS* header *MSG_TYPE* is usually modified
by the publisher to indicate what kind of data is present, either *INITIAL* of
*SNAPSHOT* is a normal response, and others have special status, *TRANSIENT* is
used for not found or not available, *DROP* is used when a subject is expired
and no longer available, *VERIFY* is used to prepare the subscriber for
updates.  In addition, the *REC_STATUS* field may contain *STALE* for out of
date records, *NOT_FOUND* when no record is present, *TEMP_UNAVAIL*,
*BAD_NAME*, *BAD_LINE*, *FEED_DOWN* for publisher errors that are not normal.
Other values can be used by the publishers, depending on the data source and
the publisher implementation.

A normal return value is:

  _INBOX.hostip.timestamp.N : {
    MSG_TYPE : INTIAL,
    REC_TYPE : NMTS,
    SEQ_NO : 1001,
    REC_STATUS : OK,
    <msg data>
  }

A Not Found return value is:

  _INBOX.hostip.timestamp.N : {
    MSG_TYPE : TRANSIENT
    REC_STATUS : NOT_FOUND
  }

A Stale return value is:

  _INBOX.hostip.timestamp.N : {
    MSG_TYPE : INTIAL,
    REC_TYPE : NMTS,
    SEQ_NO : 1001,
    REC_STATUS : STALE,
    <other data fields>
  }

The only difference for a snapshot is the *MSG_TYPE*, which will contain
*SNAPSHOT* instead of *INITIAL* in the case that a data value is returned.
The *REC_TYPE* does not need to be defined anymore, so it may be absent or
zero.

SASS3 Initial/Snapshot
^^^^^^^^^^^^^^^^^^^^^^

The *SASS3* protocol uses an header envelope which has the same semantics as
*SASS2*, but the coding of the record can be in *Marketfeed* format in addition
to the *SASS2* formats, which are *TibMsg* or *SASS Qform*.  This format may
not have the same status fields of *MSG_TYPE* and *REC_STATUS*.  The *SASS3*
envelope still uses the same status value as *SASS2*.  This is a normal return
value:

  _INBOX.hostip.timestamp.N : {
    M : pub_magic,
    T : INITIAL,
    S : OK
    D : {
      <msg data>
    }
  }

The *pub_magic* is always the value 23177.  The *T* field is equivalent to the
*MSG_TYPE* field and the *S* field is equivalent to the *REC_STATUS* field.

A Not Found return value is:

  _INBOX.hostip.timestamp.N : {
    M : pub_magic,
    T : TRANSIENT,
    S : NOT_FOUND
  }

A Stale return value is:

  _INBOX.hostip.timestamp.N : {
    M : pub_magic,
    T : INITIAL,
    S : STALE,
    D : {
      <msg data>
    }
  }

Update Publish
~~~~~~~~~~~~~~

Updates are multicast to the subscription.  These are delta changes to the
initial value.  It may be an *INITIAL* indicating all fields are present or
some other type with a subset of the fields.  An *INITIAL* is often used when
the publisher adds or removes a field from the initial value, or wants to
ensure that the subscribers are up to date by publishing the inital on a timer.

A *SASS2* update contains the same header as the initial with the *MSG_TYPE*
usually set to *UPDATE* or a status that is has additional semantics to that,
such as *CORRECT* or *CLOSING*.  

SASS2 Update
^^^^^^^^^^^^

  NASDAQ.REC.INTC.O : {
    MSG_TYPE : UPDATE,
    REC_TYPE : NMTS,
    SEQ_NO : 1002,
    REC_STATUS : OK,
    <msg data>
  }

SASS3 Update
^^^^^^^^^^^^

  NASDAQ.REC.INTC.O : {
    M : pub_magic,
    T : UPDATE,
    S : OK,
    D : {
      <msg data>
    }
  }

The *SASS3* case may omit the *T* and *S* fields as they default to these
values when not present.

Drop Notification
~~~~~~~~~~~~~~~~~

A *MSG_TYPE* which contains a *DROP* code indicates that the publisher is not
going to update a subject.  The subscription itself stays open until the
subscriber closes it.  When the *REC_STATUS* contains the status for
*NOSUBSCRIBERS*, the publisher has no active subscribers in the subscription
management database and reasserting the subscription will restart it.  This
case is rarely seen by subscribers unless they are using a wildcard.  All the
other *REC_STATUS* codes can only be reestablished by reasserting when the
subject state is reinitialized.  The subscriber can try, but the result is
usually a *NOT_FOUND* status.

SASS2 Drop
^^^^^^^^^^

This is the subscription managment notification:

  NASDAQ.REC.INTC.O : {
    MSG_TYPE : DROP,
    REC_STATUS : NOSUBSCRIBERS
  }

SASS3 Drop
^^^^^^^^^^

The *SASS3* case is the same as *SASS2* with the envelope *T* and *S* fields
set appropriately.

Subcription Expired
~~~~~~~~~~~~~~~~~~~

These are often sent when a subject bounded by a date expires.

SASS2 Expire
^^^^^^^^^^^^

This is the publisher ceasing updates on a subject:

  NASDAQ.REC.INTC.O : {
    MSG_TYPE : DROP,
    REC_STATUS : EXPIRED
  }

Subject Renamed
~~~~~~~~~~~~~~~

When a subject is moved to another, this is used to notify the subscribers.

SASS2 Relocate
^^^^^^^^^^^^^^

This is the publisher reassigning the subject to another name:

  NASDAQ.REC.INTC.O : {
    MSG_TYPE : DROP,
    REC_STATUS : RELOCATE,
    TEXT : NASDAQ.REC.MSFT.O
  }

Stale Notification
~~~~~~~~~~~~~~~~~~

A *STALE* notification is set in a *REC_STATUS* through normal update publishes
or through initial values.  It is stored with the record and is cleared only
when an *INITIAL* or a *VERIFY* clears it.  The reason for this is that a cache
does not know which field is out of date, so updates to the record are applied
and forwarded but the *STALE* status persists.

Security
--------

The transports above, mostly have *TLS* based security, and secure tunnels
could be setup between nodes at the *IP* routing layer 3, so encryption of the
transport is not a part of the security methods described here.

HMAC Authentication
~~~~~~~~~~~~~~~~~~~

This security is for the messaging layer to authenticate the publisher to the
subscribers.  The subscribers must be able to trust the messages as unmodified,
uniquely serialized, and authentic.  These methods are adapted from
link:https://en.wikipedia.org/wiki/Digest_access_authentication[Digest access
authentication].

A *HMAC* can be used to do this.  The user identity, the session instance, and
the seqno serialization of the subject's messages will be unique to the
publisher.

Each node has a database of users and services:

  [
    { user : user1, svc : service1, hash : HA0 },
    { user : user2, svc : service1, hash : HA0 },
    { user : user3, svc : service1, hash : HA0 }
  ]

Where each service identifies a subject domain:

  [
    { svc : service1,
      route : {
        type : nats,
        url : nats://127.0.0.1:4222,
        name : route,
        user : xyz,
        pass : abc,
        auth_token : tok
      }
    }
  ]

The *service1* name and the hash *HA0* are not published.  The *HA0* is a hash
of a password which may be unique to *user1* and the password is not stored on
any node.

  HA0 = SHA256( user1 + service1 + password )
  HA1 = SHA256( HA0 + NONCE )

Each message can then be authenticated to be published from the node using
*user1.NONCE* as the session prefix and using the *HA1* hash as the key in a
*HMAC* with the subject and message data resulting in the *HA2* hash.

  HA2 = AES_HASH( IV = seqno, MSG = subject + message-data )
  digest = HMAC_AES( K = HA1, MSG = HA2 )

The result is a *HMAC* authenticated message:

  subject : {
    session : user1.NONCE,
    seqno : sequence,
    digest : digest_bits,
    data {
      message-data
    }
  }

When the subscriber recieves this message, it is verified by:

  - The *seqno* must be greater than the *subjects* last message published by
    the *user1.NONCE* session to protect against replays.

  - The *user1.service1* must exist in the node database so that *HA0* can be
    computed to *HA1* using the session's *NONCE* and that can be used to
    verify the *digest*.

  - The *digest* can be recomputed using *HA0*, *HA1* and *HA2* by:
  
  HA0 = node_database[ user1.service1 ]
  HA1 = SHA256( HA0 + NONCE )
  HA2 = AES_HASH( IV = seqno, MSG = subject + message-data )
  hmac-result = HMAC_AES( K = HA1, MSG = HA2 )

To authenticate the message came from *user1.service1*, compare *hmac-result*
with *digest* in the message.  Since *HA2* is a property of the message, it can
be used to encode the *HMAC* for other transport endpoints.  *HA1* is a hash of
*HA0* and a *NONCE* which is unique to the session endpoint for *user1*, it can
be computed when the session starts.

A *HA1* hash can be computed and cached with the transport when more messages
are expected to be published from the same session.  This reduces the cost of
authentication to a *AES_HASH* of the message data and a *HMAC_AES* digest
computation, and both can be accelerated using *AES* instructions built into
the CPU.

This authentication from a publisher can only be trusted after a trust exchange
between each subscriber and pubisher, since an attacker can replay old messages
of a publisher that is no longer active.

When a publisher detects a new subscriber, this exchange ensures that old
messages are not replayed and the subscriber and publisher can trust
eachother.  More on the <<Session>> messages below.  This heartbeat is
sent by each active node and can be used by other nodes to create trust
bonds:

  _SESSION.HELLO : {
    session : newuser1.NONCE,
    seqno : sequence,
    digest : digest_bits,
    ucast_url : pgm://host:port,
    time : utc_usecs,
    interval : secs,
    cnonce : CNONCE
  }

After validating the *newuser1* message it and is not a replay of old session
by checking the *newuser1.NONCE*, *seqno* and the *utc_usecs* compared with the
system clock, a *HMAC* is computed with the information from both *newuser1*
and *publisher1*, creating a trust bond from *publisher1* to *newuser1*.

  HA0 = SHA256( publisher1 + service1 + password )
  HA1 = SHA256( HA0 + NONCE + utc_usecs + CNONCE )
  HA2 = AES_HASH( IV = seqno, MSG = subject + message-data )
  auth_digest = HMAC_AES( K = HA1, MSG = HA2 )

This is the message that *publisher1* uses to validate itself to *newuser1*:

  _INBOX.newuser1.NONCE.auth : {
    session : publisher1.NONCE,
    seqno : sequence,
    digest : auth_digest,
    auth_time : utc_usecs,
    time : utc_usecs,
    cnonce : CNONCE
  }

The *auth_time* is the time that the *_SESSION.HELLO* was sent so that the
*newuser1* has a record of sending it with the *CNONCE*.  *Newuser1* is still
not trusted by *publisher1*, only the reverse direction.  This isn't useful for
an attacker since messages published from *newuser1.NONCE* will be discarded
until it is trusted.

*Newuser1* needs to validate itself to *publisher1* using the *auth* message
sent from *publisher1.NONCE*, via the *time* and the *CNONCE* fields from
*_INBOX.newuser1.NONCE.auth* above:

  HA0 = SHA256( newuser1 + service1 + password )
  HA1 = SHA256( HA0 + NONCE + utc_usecs + CNONCE )
  HA2 = AES_HASH( IV = seqno, MSG = subject + message-data )
  auth_digest = HMAC_AES( K = HA1, MSG = HA2 )

  _INBOX.publisher1.NONCE.auth : {
    session : newuser1.NONCE,
    seqno : sequence,
    digest : auth_digest,
    auth_time : utc_usecs,
    time : utc_usecs,
    cnonce : CNONCE
  }

After this exchange, the *newuser1* adds the *publisher1.NONCE* to the trusted
list and *publisher1* adds *newuser1.NONCE*.  It is critical that *NONCE* uses
enough entropy and bits to be unique through the lifetime of the network to
protect from replays.

If an old message is replayed:

  old_subject : {
    session : oldpublisher1.NONCE,
    seqno : sequence,
    digest : digest_bits,
  }

The subscribers of this message either have a record of the last *seqno* used
by *oldpublisher1.NONCE*, or they have never created an auth bond to trust
*oldpublisher1.NONCE*.

[[Format]]
Message Presentation
--------------------

A texted based messaging system coexists well within *NATS*, *Redis*, and
*Http*, but binary formats can also coexist within the same transport.  The
text base that is most natural is a relaxed version of *JSON* used in
javascript.  The recursive field value notation of objects is compatable with
recursive self describing messaging binary formats.  The header fields required
should be limited to strings and integers so that *RV* message format can be
used without loss of semantics.  The other types of fields, such as dates,
times, decimals, etc, should have a field dictionary in order to transform from
*JSON* strings without losing information.

Binary Messages
~~~~~~~~~~~~~~~

These message formats can be extened by adding codecs.  These codecs are
recognized, in addition to *JSON*:

[grid="cols",cols="1,1,4",options="header"]
|====
| Format     | Type                  | Description
| tib_sass   | SASS Qform            | Fid fixed size value (except partials)
| tibmsg     | TibMsg                | Self describing extends SASS Qfrom
| rvmsg      | RvMsg                 | Self describing
| marketfeed | Marketfeed            | Fid value
| rwf        | Refinitiv Wire Format | Fid value, impl. Open Message Model
|====

Protocol Initialization
-----------------------

A session should be initialized at the start with a session and an inbox.

Sam and Paul
~~~~~~~~~~~~

In the example messages below, there are two users, Sam and Paul.  Sam is
the subscriber and Paul is the publisher.  A visual reference :)

image:sam_and_paul.svg[Sam and Paul]

Inbox Subjects
~~~~~~~~~~~~~~

A subscribion to an inbox endpoint, which made of an inbox prefix, a user id,
and a random *NONCE*.

An *RV* based inbox is based on the host ip address, the system clock in
seconds, the process id, and an address in the process space.  If the system
clock is reset, such as a machine rebooting, it is possible that it will
repeat.  A subject compatible user id is mobile and does not need to be tied to
a single host ip address.  The *NONCE* can be derived from a random source with
enough bits, it can provide sufficient uniqueness and security for
authentication.

If another transport is used for *_INBOX* point to point messages, that can be
specified in the session messages.  Since the *TCP* based protocols are by
their nature point to point, this only applies to *UDP* multicast trasports like
*OpenPGM*.  The *_INBOX* subjects are unique in the subject space, so they
can be multicast.

  _INBOX.USER.NONCE.>

This endpoint is used when a message is sent from node to node.  A return
can be truncated to subject without the prefix:

  _SNAP.subject : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
    return : 1,
    format : json
  }

In this case, the return would be the *_INBOX.sam.NONCE.1*.

[[Session]]
Session Notification
~~~~~~~~~~~~~~~~~~~~

A publish to a well known subject indicating a session start.

  _SESSION.HELLO : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
    ucast_url : pgm://host:port,
    time : utc_usecs,
    interval : secs,
    cnonce : CNONCE
  }

The interval is a heartbeat that keeps the sessions subscriptions alive.

  _SESSION.HB : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
    ucast_url : pgm://host:port,
    time : utc_usecs,
    interval : secs,
    cnonce : CNONCE
  }

And session stop notification causes the publishers to drop the subscriptions
associated with the session.

  _SESSION.BYE : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
  }

Subscription Operations
-----------------------

The subsciption protocol can be relatively chatty is desired, with *ack* results
so that the subcribers are informed of progress by the publishers.

Subscription Notification
~~~~~~~~~~~~~~~~~~~~~~~~~

A subscription start:

  _SUB.START.subject : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
    return : 1,
    initial : true,
    ack : true,
    format : json,
    expires : secs
  }

The expires is how long the subscription should be alive before it expires
after the last *_SESSION.HB* was seen by the publishers.  The *return* field is
specified if an initial value is wanted indicated by the *initial* field.  An
*ack* can be requested to notify that the subscription was seen by a publisher.
This would be useful when the subscription is expected to take some time or if
no initial is desired.  The *format* is a request that may not be honored if
the publisher does not use it or if there are other subscriptions started with
a different format.  The *initial* will have a format present that can be
honored.  If a *dictionary* is needed to decode the message data, then that is
also present.  This is described in <<dictionary>> section.

An *ack*:

  _INBOX.sam.NONCE.1 : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    type : start,
    subject : subject,
    status : ack
  }

An *initial* value:

  _INBOX.sam.NONCE.1 : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    type : start,
    subject : subject,
    format : json,
    dictionary : json,
    data : {
      <msg data>
    }
  }

A subscription *stop*:

  _SUB.STOP.subject : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
    return : 1,
    ack : true
  }

Like a subscription, a stop can request an *ack* return so that Sam knows
that the publisher Paul has seen the *stop* message.

  _INBOX.sam.NONCE.1 : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    type : stop,
    subject : subject,
    status : ack
  }

Wildcard Subscription
~~~~~~~~~~~~~~~~~~~~~

Since wildcards are not allowed in publishes within *NATS* and the method of
matching wildcards is different between *Redis* and the *RV* based systems,
a wildcard start has it's own notification.

A wildcard subscription start:

 _PSUB.START.prefix._ : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
    expires : secs,
    subject : prefix.>
    pattern : (?s)\Aprefix.
 }

A wildcard subscription stop:

 _PSUB.STOP.prefix._ : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
    expires : secs,
    subject : prefix.>
    pattern : (?s)\Aprefix.
 }

The prefix is the the part of the subject which matches the *RV* prefix
segments, and the pattern is a *PCRE* based match.  This allows multiple
wildcard regimes to coexist across different platforms and more complex pattern
matching.

Reassert Subscription
~~~~~~~~~~~~~~~~~~~~~

If the publisher Paul misses a heartbeat from Sam, a reassert query message
can be published to the subscriber Sam at a randomized timer in the next
interval.

  _INBOX.sam.NONCE.get_subs : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    return : sam.subs,
    last_seen : utc_usecs,
    wildcard : >
  }

If Sam has subscriptions matching the wildcard since the last_seen time
(which is relative to Sam's own clock, not Paul's), it should resend them to
Paul.  Sam can maintain a subscription window that expires after serveral
heartbeats are sent.  If the last_seen falls below the window, or is zero, then
all of the subscriptions are reasserted.

  _INBOX.paul.NONCE.sam.subs : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
    last_seen : utc_usecs,
    wildcard : >,
    initial : true,
    ack : true,
    subs : [
      subject1, subject2, ...
    ],
    subs_return : [
      1, 2
    ]
  }

For each subject that Paul publishes, an *ack* is returned to Sam as well as
the *initial* since both were specified.  The wildcard is useful since the
publishers may be listening to only a part of the subject space.

Snapshot Request
~~~~~~~~~~~~~~~~

A *snapshot* is uses a *_SNAP* prefix to indicate this is a request / reply.

  _SNAP.subject : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
    return : 1,
    format : json
  }

The value returned would be a *snapshot* value:

  _INBOX.sam.NONCE.1 : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    type : snap,
    subject : subject,
    format : json,
    data : {
      <msg data>
    }
  }

Update Messaging
----------------

Update Publish
~~~~~~~~~~~~~~

The updates are multicast to the subject of the subscription.  An update is
implied when a *type* field is not present.

  subject : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    data : {
      <msg data>
    }
  }

Drop Notification
~~~~~~~~~~~~~~~~~

When a publisher has no subscribers left, a *drop* notification is multicast to
the subject.  The status is the reason for the drop.

  subject : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    type : drop
    status : nosubscribers
  }

Not Found Notification
~~~~~~~~~~~~~~~~~~~~~~

When an *initial* or a *snapshot* is reqeusted, the not found response is
sent as a reply.

  _INBOX.sam.NONCE.1 : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    type : snap,
    subject : subject,
    status : not_found
  }

Conflated, Stale Publish
~~~~~~~~~~~~~~~~~~~~~~~~

These are forms of an update where the publisher knows that multiple messages
are lost or merged into one update.

  subject : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    status : conflated,
    data  : {
      <msg data>
    }
  }

Feed Switch Notification
~~~~~~~~~~~~~~~~~~~~~~~~

This notification an advisory that may mean messages are missing or duplicated,
out of order, since the the source has changed.  An update may be published
with the fields that are recapped having arrived within the configured period.

  subject : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    type : recap
    status : feed_switch
    data  : {
      <msg data>
    }
  }

Type and Status Usage
---------------------

A type and status are optionally used by publishers to indicate how the message
should be handled.  The default values of type and status are *update* and
*ok*.  The following are the most useful of the type/status combinations.
There are many more status codes that are defined, but are rarely used.  The
type enumeration is the most complete.  The caching semantics of *initial*,
*drop*, *update*, *verify*, *snap* are well defined without the need for other
operators.  A *transient* operator is the same as a status without message
data.  A source of *bad_name* status is a translation from subject to
instrument failure, creating an incompatible *RV* subject, such as empty
segments created by multiple '.' concatenated.  A *bad_access* status is the
result of a request that creates an invalid instrument name. The *temp_unavail*
is the result of an unresponsive publisher, when a timer expires or when there
is corruption in a database that was taken offline.  A *perm_denied* is an
explicit denial because the request doesn't have the required permissions.

[grid="cols",cols="1,1,4",options="header"]
|====
| Type    | Status        | Description
| start   | ack           | Ack requested with start request
| stop    | ack           | Ack requested with stop request
| snap    | ok            |
|  "      | not_found     | Message not cached
|  "      | temp_unavail  | Subject timed out or connectivity issue
|  "      | bad_access    | Subject rejected by source
|  "      | bad_name      | Subject naming scheme incompatable with source
|  "      | feed_down     | Subject source is offline, value is stale
|  "      | stale         | Value is old, incomplete
|  "      | perm_denied   | Subscriber permission denied
| initial | ok            |
|  "      | verify        | Message was reinitialized
|  "      | not_found     | Message not cached
|  "      | temp_unvail   | Subject timed out or connectivity issue
|  "      | bad_access    | Subject rejected by source
|  "      | bad_name      | Subject naming scheme incompatable with source
|  "      | stale         | Value is old, incomplete
|  "      | conflated     | Message merged updates
|  "      | feed_down     | Subject source is offline, value is stale
|  "      | feed_switch   | New publisher, may have missing updates
|  "      | perm_denied   | Subscriber permission denied
| drop    | nosubscribers | No subscribers left
|  "      | expired       | The publisher is no longer updating subject
|  "      | relocate      | New subject name
|  "      | preempted     | Cache full, message discarded
| update  | ok            |
|  "      | stale         | Updating stale message
|  "      | conflated     | Message merged updates
|  "      | feed_down     | Subject source is offline, value is stale
|  "      | temp_unvail   | Subject timed out or connectivity issue
|  "      | bad_access    | Subject rejected by source
|  "      | bad_name      | Subject naming scheme incompatable with source
|  "      | perm_denied   | Subscriber permission denied
| verify  | ok            | Update that clears or validates fields
|====

[[dictionary]]
Dictionaries
------------

Some message formats require a dictionary to decode.  When a message from a
publisher sends one of these formats, it will have a dictionary field in the
*initial* and the *snap* values sent to the subscribers, with an optional
dictionary checksum when it is expected to be changed.  If a dictionary is
modified while the publisher is updating the subject stream, the publisher
should send an initial with the new dictionary checksum.

  _INBOX.sam.NONCE.1 : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    type : start,
    subject : subject,
    format : json,
    dictionary : json,
    dict_csum : 0x12345678,
    data : {
      <msg data>
    }
  }

The subscribers must be able to get the dictionary from the publisher using
the *session* field, constructing a request reply with name and optional
checksum:

  _INBOX.paul.NONCE.dict : {
    session : sam.NONCE,
    seqno : sequence,
    digest : digest_bits,
    dictionary : json,
    dict_csum : 0x12345678,
    return : 1
  }

The response will from this dictionary request:

  _INBOX.sam.NONCE.1 : {
    session : paul.NONCE,
    seqno : sequence,
    digest : digest_bits,
    dictionary : json
    dict_csum : 0x12345678,
    data : {
      <dictionary>
    }
  }

